# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0005_auto_20150318_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='col_1_1',
            new_name='c1_1',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_1_2',
            new_name='c1_2',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_1_3',
            new_name='c1_3',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_1_4',
            new_name='c1_4',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_1_5',
            new_name='c1_5',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_1_6',
            new_name='c1_6',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_1_7',
            new_name='c1_7',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_1_8',
            new_name='c1_8',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_2_1',
            new_name='c2_1',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_2_2',
            new_name='c2_2',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_2_3',
            new_name='c2_3',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_2_4',
            new_name='c2_4',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_2_5',
            new_name='c2_5',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_3_1',
            new_name='c3_1',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_3_5',
            new_name='c3_5',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_3_6',
            new_name='c3_6',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_3_7',
            new_name='c3_7',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_3_8',
            new_name='c3_8',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_4_1',
            new_name='c4_1',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_4_2',
            new_name='c4_2',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_4_3',
            new_name='c4_3',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_4_4',
            new_name='c4_4',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_4_5',
            new_name='c4_5',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_4_6',
            new_name='c4_6',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_4_7',
            new_name='c4_7',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='col_4_8',
            new_name='c4_8',
        ),
    ]
